language: python

install:
    - python -m pip install -r requirements.txt

# TODO run pyvows tests, nosetests ignores them
script:
    - nosetests --with-doctest gotchas
    - nosetests --with-coverage --cover-package=design_patterns design_patterns
    - nosetests jam
    - nosetests cellular_automaton
    - nosetests mini_sim
    - nosetests mini_game

after_success:
    - coveralls
