language: python

install:
    - python -m pip install -r requirements.txt

# --with-doctest causes nosetests to execute all py modules
# TODO make sure py modules do not get executed
# TODO run pyvows tests, nosetests ignores them
script:
    - nosetests --with-doctest gotchas
    - nosetests --with-coverage --cover-package=design_patterns design_patterns
    - nosetests jam
    - nosetests cellular_automaton
    - nosetests mini_sim

after_success:
    - coveralls
