language: python

install:
  - pip install -r requirements.txt

# --with-doctest causes nosetests to execute all py modules
# TODO make sure py modules do not get executed
script: nosetests --with-doctest designPatterns gotchas
